// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fastSplitC
CharacterVector fastSplitC(String s, String delim);
RcppExport SEXP _fastSplitR_fastSplitC(SEXP sSEXP, SEXP delimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< String >::type s(sSEXP);
    Rcpp::traits::input_parameter< String >::type delim(delimSEXP);
    rcpp_result_gen = Rcpp::wrap(fastSplitC(s, delim));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fastSplitR_fastSplitC", (DL_FUNC) &_fastSplitR_fastSplitC, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_fastSplitR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
