# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastSplitC <- function(s, delim) {
    .Call(`_fastSplitR_fastSplitC`, s, delim)
}

fastSplitZ <- function(s) {
    .Call(`_fastSplitR_fastSplitZ`, s)
}

